### ISSUE TITLE
Fix navigation link color

### ISSUE THREAD

**Issue by krishxmatta** [krishxmatta/krishxmatta.dev#17]
Navigation link colors are darker than should be.

**Comment by Zaibi1** [comment]
Hi Krish!
Allow me this issue I can fix it.

**Comment by krishxmatta** [comment]
Feel free to submit a PR @Zaibi1.

**Comment by Zaibi1** [comment]
@krishxmatta can you please guide me. Are you talking about this page public/index.html navigation links?
